# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    
    environment:
      POSTGRES_PASSWORD: ferry1234
      POSTGRES_USER: ferry
   

  